### ISSUE TITLE
Container not starting. Config file not found.

### ISSUE THREAD

**Issue by parmeetdx** [brchri/tesla-geogdo#22]
I'm getting this error when starting the container - `05/11/2024 12:18:07 [  ] Config file /app/config/config.yml doesn't exist!`

I used this to create the container

```
version: '3.8'
services:
  tesla-geogdo:
    image: brchri/tesla-geogdo:latest
    container_name: tesla-geogdo
    environment:
      - TZ=America/Los_Angeles # optional, sets timezone for container
    ports:
      - 8555:8555 # optional, only needed to use api
    volumes:
      - /volume1/docker/tesla-geogdo:/app/config # required, mounts folder containing config file(s) into container
    restart: unless-stopped
```

Where do I need to keep the config file?
