### ISSUE TITLE
http POST command

### ISSUE THREAD

**Issue by DjAnu** [brchri/tesla-geogdo#4]
Hey Hi, Hope you are doing well. While I am still waiting for my Ratgdo. I looked into your Geogdo App and see there is an option to POST http commands. I can send http commands to open/close my garage door however my end point URL looks like this:

"http://192.168.0.18/apps/api/195/devices/389/close?access_token=b04b23fb-b779-4998-929"
Also my garage door doesn't take status command. There is a refresh command but that yields bunch of information along with status so I am assuming I can't use that.

Can you help me on how to implement this on your config.yml file ?

**Comment by brchri** [comment]
Sure, so your config would look like this:

```yml
    opener:
      type: http
      settings:
        connection:
          host: 192.168.0.18
          port: 80
        commands:
          - name: open
            endpoint: /apps/api/195/devices/389/open?access_token=b04b23fb-b779-4998-929
            http_method: post
          - name: close
            endpoint: /apps/api/195/devices/389/close?access_token=b04b23fb-b779-4998-929
            http_method: post
```

As you mentioned, if your status isn't a simple "open" or "closed" response, then it won't work; it's too difficult to try to account for every possible HTTP response. Therefore GeoGDO won't be able to check a required start state or that the command executed successfully (other than based on the HTTP response code).

Hope that helps.

**Comment by DjAnu** [comment]
Thanks for your quick response. I had used the endpoints as you suggested above but I didn't remove other code lines. But in logs I was seeing command sent although it didn't work. I just updated the config file as above and got 405 error in logs. Any idea ? 
Also is it possible to enable detailed logs ?
For now I can ignore status, I'll wait for Ratgdo to arrive, I placed the order on 10/28 so still waiting.

![image](https://github.com/brchri/tesla-geogdo/assets/5419410/6b5d5a5d-af85-4eb5-ae0b-a35045d291c6)

**Comment by brchri** [comment]
Yeah honestly I expected that it would've been a `get` request based on that endpoint. So try replacing `post` with `get` and see if it does any better. You can also set an environment variable to `DEBUG=true` for more verbose logging, though there's not much logic to that particular package so it might not give you much more relevant information.

**Comment by DjAnu** [comment]
Great, Seems like it worked. When I go home I'll check if it operated as intended. Thanks so much for your help. 

![image](https://github.com/brchri/tesla-geogdo/assets/5419410/878f476e-4935-4e64-844e-5bb66f165fc6)

**Comment by brchri** [comment]
Sure thing, let me know! You're my first guinea pig with an HTTP-based GDO, when I wrote it I just had simulated tests to validate, so I'd be interested if you have any issues with it.

**Comment by DjAnu** [comment]
Of course, going home now. Will test and report back when I get home. Ha ha.

**Comment by DjAnu** [comment]
Strangely I noticed this morning app is trying to send open/close commands repeatedly. Not sure why. There should have only been 1 close command since I was leaving from home. Any idea why ? And this is while I have the cooldown set to 5 min.

Never had such incidence with YouQ even though cooldown was set to 0.

**Comment by brchri** [comment]
Whoa, that's weird for 2 reasons:

1. Obviously the cooldown should prevent this
2. Even without the cooldown, it should only trigger when you actually cross a geofence, but that looks like it's trying to trigger it on every new update even after you're already in the geofence (and therefore no longer crossing it).

If you want to send me your (scrubbed) config I can take a look and see if I can figure out what's going on.

**Comment by DjAnu** [comment]
Here you go.

[config.yml.txt](https://github.com/brchri/tesla-geogdo/files/13443716/config.yml.txt)

**Comment by DjAnu** [comment]
Yeah surprisingly it happened this morning only. Logs from couple of events yesterday seems to be fine

**Comment by brchri** [comment]
Okay the first problem is your indentation on the `cooldown` line. You have it currently set as a subsetting of `teslamate_mqtt_settings.connection`, when it should be a subsetting of `global`.  Try moving it above your `tesla_mqtt_settings`, like this:

```yaml
global:
  cooldown: 5
  teslamate_mqtt_settings:
    <other stuff>
```

That should at least prevent the spam for now. It still shouldn't have been doing it, I'll keep looking into that, but that should at least prevent your spam for now.
